# Isi file manhattan_theme.conf
include kitty.conf

# Pale Gold Manhattan Cafe
color3  #EEE8AA
color11 #FFFACD
background_opacity 0.8

font_family      JetBrainsMono Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size        12.0
