general {
    lock_cmd = pidof hyprlock || hyprlock       # Perintah buat ngunci (cek biar gak double)
    before_sleep_cmd = loginctl lock-session    # Kunci layar dulu sebelum tidur
    after_sleep_cmd = hyprctl dispatch dpms on  # Nyalakan layar pas bangun
}

listener {
    timeout = 900                                # 15 Menit diam
    on-timeout = brightnessctl -s set 30         # Redupkan layar ke 30% (simpan nilai lama)
    on-resume = brightnessctl -r                 # Balikkan terang layar pas gerak mouse
}

listener {
    timeout = 1200                               # 20 Menit diam
    on-timeout = loginctl lock-session           # Kunci Layar (Panggil Hyprlock)
}

listener {
    timeout = 2700                               # 45 Menit diam
    on-timeout = hyprctl dispatch dpms off       # Matikan Layar (Layar hitam total)
    on-resume = hyprctl dispatch dpms on         # Nyalakan lagi pas ada aktivitas
}

listener {
    timeout = 3000                               # 50 Menit diam
    on-timeout = systemctl suspend               # Suspend (Tidur)
}
